apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: household-hub-frontend
  namespace: household-hub
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
